// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1NOJ4J4gWCYxxtaRrvrrFmhDJvhq7cg',
    appId: '1:914739351348:web:47643b3beac0406f461f61',
    messagingSenderId: '914739351348',
    projectId: 'eelu-student-planner',
    authDomain: 'eelu-student-planner.firebaseapp.com',
    storageBucket: 'eelu-student-planner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9N23tejXnkcnKcjDkpTlCNJDZFzfu4hA',
    appId: '1:914739351348:android:7ab7b1e255ff0a8a461f61',
    messagingSenderId: '914739351348',
    projectId: 'eelu-student-planner',
    storageBucket: 'eelu-student-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuZULwrcjzW9xQQw4FLCzZn-kDOL0r_BE',
    appId: '1:914739351348:ios:76f6e62ab22c12d9461f61',
    messagingSenderId: '914739351348',
    projectId: 'eelu-student-planner',
    storageBucket: 'eelu-student-planner.firebasestorage.app',
    androidClientId: '914739351348-c792ivam6sgg2ddvoslunggn6k22mna3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eeluStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuZULwrcjzW9xQQw4FLCzZn-kDOL0r_BE',
    appId: '1:914739351348:ios:76f6e62ab22c12d9461f61',
    messagingSenderId: '914739351348',
    projectId: 'eelu-student-planner',
    storageBucket: 'eelu-student-planner.firebasestorage.app',
    androidClientId: '914739351348-c792ivam6sgg2ddvoslunggn6k22mna3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eeluStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm1NOJ4J4gWCYxxtaRrvrrFmhDJvhq7cg',
    appId: '1:914739351348:web:c17eb688f0c42092461f61',
    messagingSenderId: '914739351348',
    projectId: 'eelu-student-planner',
    authDomain: 'eelu-student-planner.firebaseapp.com',
    storageBucket: 'eelu-student-planner.firebasestorage.app',
  );
}
