import 'dart:developer';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

import '../utils/egypt_time.dart';

class PlannerReminder {
  const PlannerReminder({
    required this.id,
    required this.titleEn,
    required this.titleAr,
    required this.bodyEn,
    required this.bodyAr,
    required this.eventAt,
    this.notificationAt,
  });

  final String id;
  final String titleEn;
  final String titleAr;
  final String bodyEn;
  final String bodyAr;
  final DateTime eventAt;
  final DateTime? notificationAt;
}

/// Owns only device-local scheduled reminders.
///
/// These reminders are generated by the student app itself.
/// Supabase/FCM are NOT responsible for lecture/quiz reminders.
class LocalNotificationScheduler {
  LocalNotificationScheduler._();

  static final LocalNotificationScheduler instance =
      LocalNotificationScheduler._();

  static const int plannerTaskIdStart = 700000;
  static const int plannerLectureIdStart = 800000;

  static const String channelId = 'planner_reminders';

  final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();

  bool _initialized = false;
  bool _initializationFailed = false;

  /// Initializes local notifications safely.
  ///
  /// If Android notification initialization fails, the app must continue
  /// normally. The failure is logged and reminder scheduling is skipped.
  Future<bool> initialize() async {
    if (_initialized) {
      return true;
    }

    if (_initializationFailed) {
      return false;
    }

    try {
      EgyptTime.initialize();

      const details = InitializationSettings(
        android: AndroidInitializationSettings('ic_notification'),
      );

      await _plugin.initialize(
        settings: details,
      );

      final android = _plugin.resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>();

      await android?.createNotificationChannel(
        const AndroidNotificationChannel(
          channelId,
          'Planner Reminders',
          description:
              'Reminders for lectures, assignments, quizzes and exams.',
          importance: Importance.high,
        ),
      );

      await android?.requestNotificationsPermission();

      _initialized = true;

      log(
        'Local notifications initialized successfully.',
        name: 'LocalNotifications',
      );

      return true;
    } catch (error, stackTrace) {
      _initializationFailed = true;

      log(
        'Local notifications initialization failed: $error',
        name: 'LocalNotifications',
        stackTrace: stackTrace,
      );

      return false;
    }
  }

  Future<void> replaceReminders(
    List<PlannerReminder> reminders, {
    int idStart = plannerTaskIdStart,
  }) async {
    final initialized = await initialize();

    if (!initialized) return;

    try {
      // Cancel only reminders owned by this planner range.
      final pending = await _plugin.pendingNotificationRequests();
      for (final request in pending) {
        if (request.id >= idStart && request.id < idStart + 100000) {
          await _plugin.cancel(id: request.id);
        }
      }

      final isLectureReminder = idStart == plannerLectureIdStart;
      final now = EgyptTime.now();

      // We deliberately use inexact scheduling. The reminders are calendar
      // reminders, not alarms that require second-level precision, and this
      // avoids Android's exact-alarm permission requirement.
      const scheduleMode = AndroidScheduleMode.inexactAllowWhileIdle;

      var index = 0;

      for (final reminder in reminders) {
        final notificationAt = reminder.notificationAt ?? reminder.eventAt;
        if (!notificationAt.isAfter(now)) continue;

        try {
          await _plugin.zonedSchedule(
            id: idStart + index,
            // Notification content is always Arabic, regardless of the app UI language.
            title: reminder.titleAr,
            body: reminder.bodyAr,
            scheduledDate: tz.TZDateTime.from(notificationAt, tz.local),
            notificationDetails: const NotificationDetails(
              android: AndroidNotificationDetails(
                channelId,
                'Planner Reminders',
                channelDescription:
                    'Reminders for lectures, assignments, quizzes and exams.',
                importance: Importance.high,
                priority: Priority.high,
                icon: 'ic_notification',
              ),
            ),
            androidScheduleMode: scheduleMode,
            payload: reminder.id,
          );

          log(
            'Scheduled ${isLectureReminder ? 'lecture' : 'deadline'} reminder '
            '${reminder.id} at $notificationAt',
            name: 'LocalNotifications',
          );
          index++;
        } catch (error, stackTrace) {
          log(
            'Failed to schedule reminder ${reminder.id}: $error',
            name: 'LocalNotifications',
            stackTrace: stackTrace,
          );
        }
      }

      log(
        'Scheduled $index planner reminders.',
        name: 'LocalNotifications',
      );
    } catch (error, stackTrace) {
      log(
        'Replacing planner reminders failed: $error',
        name: 'LocalNotifications',
        stackTrace: stackTrace,
      );
    }
  }

  Future<void> cancelPlannerReminders() async {
    final initialized = await initialize();

    if (!initialized) {
      return;
    }

    try {
      final pending = await _plugin.pendingNotificationRequests();

      for (final request in pending) {
        final isTaskReminder = request.id >= plannerTaskIdStart &&
            request.id < plannerTaskIdStart + 100000;

        final isLectureReminder = request.id >= plannerLectureIdStart &&
            request.id < plannerLectureIdStart + 100000;

        if (isTaskReminder || isLectureReminder) {
          await _plugin.cancel(id: request.id);
        }
      }
    } catch (error, stackTrace) {
      log(
        'Failed to cancel planner reminders: $error',
        name: 'LocalNotifications',
        stackTrace: stackTrace,
      );
    }
  }

  Future<void> showScheduledTestNotification() async {
    final initialized = await initialize();

    if (!initialized) {
      return;
    }

    try {
      final when = EgyptTime.now().add(
        const Duration(minutes: 1),
      );

      await _plugin.zonedSchedule(
        id: plannerTaskIdStart - 2,
        title: 'EELU Student Planner',
        body: 'Scheduled local notification test.',
        scheduledDate: tz.TZDateTime.from(
          when,
          tz.local,
        ),
        notificationDetails: const NotificationDetails(
          android: AndroidNotificationDetails(
            channelId,
            'Planner Reminders',
            channelDescription:
                'Reminders for lectures, assignments, quizzes and exams.',
            importance: Importance.high,
            priority: Priority.high,
            icon: 'ic_notification',
          ),
        ),
        androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle,
        payload: 'test-scheduled',
      );
    } catch (error, stackTrace) {
      log(
        'Failed to schedule test notification: $error',
        name: 'LocalNotifications',
        stackTrace: stackTrace,
      );
    }
  }

  Future<void> showTestNotification() async {
    final initialized = await initialize();

    if (!initialized) {
      return;
    }

    try {
      await _plugin.show(
        id: plannerTaskIdStart - 1,
        title: 'EELU Student Planner',
        body: 'Local notification test succeeded.',
        notificationDetails: const NotificationDetails(
          android: AndroidNotificationDetails(
            channelId,
            'Planner Reminders',
            channelDescription:
                'Reminders for lectures, assignments, quizzes and exams.',
            importance: Importance.high,
            priority: Priority.high,
            icon: 'ic_notification',
          ),
        ),
      );
    } catch (error, stackTrace) {
      log(
        'Failed to show test notification: $error',
        name: 'LocalNotifications',
        stackTrace: stackTrace,
      );
    }
  }
}