import 'package:flutter/material.dart';

import 'app_localizations_ar.dart';
import 'app_localizations_en.dart';

abstract class AppLocalizations {
  const AppLocalizations();

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String get settings;
  String get preferences;
  String get notifications;
  String get darkMode;
  String get language;
  String get account;
  String get profile;
  String get academicInformation;
  String get general;
  String get aboutApp;
  String get contactAndLinks;
  String get logout;
  String get home;
  String get quickActions;
  String get keepGoing;
  String get studentDashboard;
  String get myUniversity;
  String get courses;
  String get noCourses;
  String get failedToLoadCourses;
  String get calendar;
  String get managePreferences;
  String get receiveReminders;
  String get testNotification;
  String get testNotificationSent;
  String get scheduledTestNotification;
  String get useDarkAppearance;
  String get editPersonalInformation;
  String get levelAndGroup;
  String get courseGroupsSelected;
  String get courseGroupsTitle;
  String get noCourseGroupsSelected;
  String get english;
  String get arabic;
  String get profileTitle;
  String get editProfile;
  String get name;
  String get email;
  String get role;
  String get level;
  String get group;
  String get university;
  String get major;
  String get informationTechnology;
  String get student;
  String get notSet;
  String get failedToLoadProfile;
  String get profileNotFound;
  String get academicInformationTitle;
  String get aboutAppTitle;
  String get contactAndLinksTitle;
  String get appDescription;
  String get appVersion;
  String get coursesLabel;
  String get scheduleLabel;
  String get addTask;
  String get viewSchedule;
  String get tasksLabel;
  String get quizzesLabel;
  String get examsLabel;
  String get lecturesLabel;
  String get whatsapp;
  String get emailContact;
  String get linkedin;
  String get github;
  String get contactWhatsappDescription;
  String get contactEmailDescription;
  String get contactLinkedinDescription;
  String get contactGithubDescription;
  String get unableToOpenLink;
  String get requiredField;
  String get invalidLevel;
  String get profileUpdated;
  String get department;
  String get academicYear;
  String get addExam;
  String get editExam;
  String get upcoming;
  String get past;
  String get all;
  String get nextExam;
  String get noExams;
  String get course;
  String get examType;
  String get date;
  String get startTime;
  String get endTime;
  String get location;
  String get saveExam;
  String get deleteExam;
  String get deleteExamConfirmation;
  String get examSaved;
  String get edit;
  String get delete;
  String get cancel;
  String get examsTitle;
  String get deleteExamMessage;
  String get quiz;
  String get midterm;
  String get finalExam;
  String get examDate;
  String get examTime;
  String get examLocation;
  String get upcomingExams;
  String get pastExams;
  String get examsSubtitle;
  String get today;
  String get tomorrow;
  String examDaysLeft(int days);
  String get nextDeadline;
  String get upcomingDeadlines;
  String get viewAll;
  String get offlineUsingCachedData;
  String get refreshSucceeded;
  String get daysLeft;
  String get overdue;
  String get allCaughtUp;
  String get noUpcomingDeadlines;
  String get task;
  String get assignment;
  String get personalAssignment;
  String get universityAssignment;
  String get personalTask;
  String get pending;
  String get completed;
  String get status;
  String get type;
  String get addPersonalTask;
  String get editPersonalTask;
  String get deletePersonalTask;
  String get deletePersonalTaskConfirmation;
  String get noUniversityAssignmentsOrPersonalTasks;
  String get noQuizzesAvailable;
  String get noPersonalTasksHint;
  String get quizzesForSelectedCourses;
  String get tasksSubtitle;
  String get exam;
  String get lecturesTitle;
  String get addLecture;
  String get editLecture;
  String get filterByCourse;
  String get noLectures;
  String get deleteLecture;
  String get deleteLectureMessage;
  String get future;
  String get todayLectures;
  String get upcomingLectures;
  String get addLectureTitle;
  String get lectureTitle;
  String get instructor;
  String get starts;
  String get ends;
  String get description;
  String get content;
  String get saveChanges;
  String get required;
  String get unread;
  String get markAllRead;
  String get deleteAllNotifications;
  String get deleteAllNotificationsConfirmation;
  String get noNotifications;
  String get noUnreadNotifications;
  String get notificationsError;
  String get courseDetails;
  String get upcomingTasks;
  String get noUpcomingTasks;
  String get noUpcomingExams;
  String get noUpcomingLectures;
  String get courseInformation;
  String get section;
  String get taskDetails;
  String get assignmentDetails;
  String get quizDetails;
  String get personalAssignmentDetails;
  String get examDetails;
  String get lectureDetails;
  String get taskType;
  String get priority;
  String get detailsUnavailable;
  String get courseNotFound;

  String get appName;
  String get passwordsDoNotMatch;
  String get confirmPasswordRequired;
  String get passwordTooShort;
  String get invalidName;
  String get login;
  String get alreadyHaveAccount;
  String get createAccountButton;
  String get repeatPassword;
  String get confirmPassword;
  String get createPassword;
  String get password;
  String get enterEmail;
  String get enterName;
  String get startOrganizing;
  String get appTagline;
  String get welcomeBack;
  String get googleLoginDescription;
  String get studentIdAfterGoogle;
  String get completeProfile;
  String get studentIdDescription;
  String get studentId;
  String get studentIdHint;
  String get signInWithGoogle;
  String get continueLabel;
  String get selectCoursesTitle;
  String get selectCoursesDescription;
  String get selectAtLeastOneCourse;
  String get saveCourses;
  String get selectedCoursesCount;
  String get noCoursesForGroup;
  String get noCourseOfferingsAvailable;
  String get chooseGroupForCourse;
  String get courseGroupsCanDiffer;
  String get invalidStudentId;
  String get studentAccountNotFound;
  String get studentIdAlreadyLinked;
  String get or;
  String get contactLinks;
  String get lectureProgress;
  String get overallLectureProgress;
  String get yourLectureProgress;
  String get studied;
  String get completedPercentage;
  String get lecturesCount;
  String get courseProgress;
  String get noCoursesProgress;
  String get noLecturesFound;
  String get failedToLoadLectureProgress;
  String get failedToUpdateLectureProgress;
  String get retry;
  String get todaySchedule;
  String get noLecturesToday;
  String get classesCount;
  String get calendarTitle;
  String get calendarSubtitle;
  String get noLecturesSelectedDay;
  String get doctor;
  String get doctorEmail;
  String get copy;
  String get copied;
  String get levelLabel;
  String get groupLabel;
  String get yourGroup;
  String get courseMaterials;
  String get youtubePlaylist;
  String get instructors;
  String get yourInstructor;
  String get otherInstructor;
  String get chooseInstructorForMaterials;
  String get chooseInstructorForPlaylist;
  String get noResourceAvailable;
  String get lectureSchedule;
  String get online;
  String get offline;
  String get lectureTime;
  String get failedToLoadSchedule;
  String get imageUploadFailed;
  String get imageNotFound;
  String get unsupportedImage;
  String get unableToLoadProfile;
  String get unableToUpdateProfile;
  String get genericError;
  String get networkError;
  String get databaseError;
  String get googleSignInFailed;
  String get invalidCredentials;
  String get emailNotConfirmed;
  String get userAlreadyRegistered;
  String get invalidEmail;
  String get weakPassword;
  String get rateLimit;
  String get appLoading;
  String get createAccount;

  static const delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return locale.languageCode == 'en' || locale.languageCode == 'ar';
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return locale.languageCode == 'ar'
        ? const AppLocalizationsAr()
        : const AppLocalizationsEn();
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
